language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install -y libxml2 libxml2-dev
install:
  - python3 -m pip install gillespy2
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install sphinx
  - pip install sphinx-rtd-theme
  - pip install .
# tests should run from the tests directory
before_script:
  - wget https://github.com/StochSS/StochKit/archive/master.zip
  - unzip master.zip
  - cd StochKit-master
  - ./install.sh
  - export STOCHKIT_HOME=$PWD
  - cd ..
  - cd sciope/tests
# command to run tests
script: travis_wait 30 py.test  --cov-report term --cov
after_success:
  - codecov
  - cd docs && make html
# deploy to Github pages
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: develop
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true
